// src/components/PageTitle.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { ArrowLeft } from '@lucide/svelte';
	import { cn } from '$lib/utils';

	type Props = {
		title: string;
		showBackButton?: boolean
	}

	let { title, showBackButton = false }: Props = $props();

	const goBack = () => {
		window.history.back();
	};
</script>

<div class={cn(
	"mb-9 flex w-full items-center justify-center",
	"bg-gradient-to-b from-black/40 to-transparent"
	)}>
	{#if showBackButton}
		<Button type="button" variant="outline"
						class="mr-8 flex-0 cursor-pointer" onclick={goBack}>
			<ArrowLeft size="24" />
		</Button>
	{/if}

	<h1 class="font-serif text-4xl text-foreground">{title}</h1>
</div>

// app/components/PageTitle.tsx
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';

type PageTitleProps = {
	title: string;
	showBackButton?: boolean;
};

export default function PageTitle({
	title,
	showBackButton = false,
}: PageTitleProps) {
	const goBack = () => {
		window.history.back();
	};

	return (
		<div className="mb-9 flex w-full items-center justify-center">
			{showBackButton && (
				<Button
					type="button"
					variant="outline"
					className="mr-8 flex-0 cursor-pointer"
					onClick={goBack}
				>
					<ArrowLeft size="20" />
				</Button>
			)}

			<h1 className="font-serif text-4xl text-foreground">{title}</h1>
		</div>
	);
}
