// app/components/MobileMenu.tsx
import { Link } from 'react-router';
import { useSession } from '@/lib/auth-client';
import { cn } from '@/lib/utils';

type MobileMenuProps = {
	isOpen: boolean;
	onClose: () => void;
};

export default function MobileMenu({ isOpen, onClose }: MobileMenuProps) {
	const session = useSession();

	const closeOnClick = () => {
		if (onClose) {
			onClose();
		}
	};

	return (
		<div
			className={cn(
				'mobile-menu fixed inset-0 z-100 h-full min-h-full w-full bg-secondary p-4',
				!isOpen && 'hidden',
			)}
		>
			<header className="flex items-center justify-center">
				<h1 className="text-foreground text-xl">Menu</h1>
			</header>
			<nav>
				<ul className="flex flex-col items-start justify-start gap-4">
					<li>
						<Link to="/leaderboard" onClick={() => closeOnClick()}>
							Classifica
						</Link>
					</li>
					<li>
						<Link to="/tournaments" onClick={() => closeOnClick()}>
							Tornei
						</Link>
					</li>

					{session?.data?.user && session?.data?.user.role === 'admin' && (
						<li>
							<Link to="/admin" onClick={() => closeOnClick()}>
								Amministrazione
							</Link>
						</li>
					)}

					<li className="logout">
						<form action="/logout" method="POST">
							<button type="submit">Esci</button>
						</form>
					</li>
				</ul>
			</nav>
		</div>
	);
}

// src/components/MobileMenu.svelte
<script lang="ts">
	import { cn } from '$lib/utils';

	let { open, user, onClose } = $props();

	const closeOnClick = () => {
		if (onClose) {
			onClose();
		}
	};
</script>

<div class={cn(
	"mobile-menu fixed w-screen h-screen top-0 left-0 bg-background p-4",
	"z-100 translate-x-full transition-transform duration-500",
	open && "translate-x-0",
	)}>
	<header class="flex justify-center items-center h-16">
		<h1 class="text-5xl">Menu</h1>
	</header>
	<nav>
		<ul class="flex flex-col gap-4 mt-12">
			<li class="h-12">
				<a class="text-3xl" href="/leaderboard" onclick={()=> closeOnClick()}>Classifica</a>
			</li>
			<li class="h-12">
				<a class="text-3xl" href="/tournaments" onclick={()=> closeOnClick()}>Tornei</a>
			</li>

			{#if user && user?.role === 'admin'}
				<li class="h-12">
					<a class="text-3xl" href="/admin" onclick={()=> closeOnClick()}>Amministrazione</a>
				</li>
			{/if}

			<li class="h-12">
				<form action="/logout" method="POST">
					<button type="submit" class="text-3xl">Esci</button>
				</form>
			</li>
		</ul>
	</nav>
</div>
