// app/components/MobileMenu.tsx
import { Link } from 'react-router';
import { useSession } from '@/lib/auth-client';
import { cn } from '@/lib/utils';

type MobileMenuProps = {
	isOpen: boolean;
	onClose: () => void;
};

export default function MobileMenu({ isOpen, onClose }: MobileMenuProps) {
	const session = useSession();

	const closeOnClick = () => {
		if (onClose) {
			onClose();
		}
	};

	return (
		<div
			className={cn(
				'mobile-menu fixed inset-0 z-100 h-full min-h-full w-full bg-secondary p-4',
				!isOpen && 'hidden',
			)}
		>
			<header className="flex items-center justify-center">
				<h1 className="text-foreground text-xl">Menu</h1>
			</header>
			<nav>
				<ul className="flex flex-col items-start justify-start gap-4">
					<li>
						<Link to="/leaderboard" onClick={() => closeOnClick()}>
							Classifica
						</Link>
					</li>
					<li>
						<Link to="/tournaments" onClick={() => closeOnClick()}>
							Tornei
						</Link>
					</li>

					{session?.data?.user && session?.data?.user.role === 'admin' && (
						<li>
							<Link to="/admin" onClick={() => closeOnClick()}>
								Amministrazione
							</Link>
						</li>
					)}

					<li className="logout">
						<form action="/logout" method="POST">
							<button type="submit">Esci</button>
						</form>
					</li>
				</ul>
			</nav>
		</div>
	);
}

// __old/src/components/MobileMenu.svelte
<script lang="ts">
	export let open: boolean = false;
	export let user;
	export let onClose: () => void;

	const closeOnClick = () => {
		if (onClose) {
			onClose();
		}
	};
</script>

<div class="mobile-menu" class:is-open={open}>
	<header>
		<h1>Menu</h1>
	</header>
	<nav>
		<ul>
			<li>
				<a href="/leaderboard" on:click={()=> closeOnClick()}>Classifica</a>
			</li>
			<li>
				<a href="/tournaments" on:click={()=> closeOnClick()}>Tornei</a>
			</li>

			{#if user && user?.role === 'admin'}
				<li>
					<a href="/admin" on:click={()=> closeOnClick()}>Amministrazione</a>
				</li>
			{/if}

			<li class="logout">
				<form action="/logout" method="POST">
					<button type="submit">Esci</button>
				</form>
			</li>
		</ul>
	</nav>
</div>

<style lang="scss">
  .mobile-menu {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    padding: 0 1rem 1rem 1rem;
    background: var(--color-dark);
    transform: translate3d(100%, 0, 0);
    transition: transform 0.5s ease-in-out;
    z-index: 100;

    &.is-open {
      transform: translateX(0);
    }

    header {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 48px;
      margin: 0 0 3rem 0;
    }

    h1 {
      /* height: 48px; */
      margin: 0;
      font-family: var(--variable-font-family-default);
      font-size: var(--text-scale-20);
      line-height: 1;
      color: var(--color-white);
    }

    ul,
    li {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }

    ul {
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      align-items: flex-start;
    }

    li {
      &.logout {
        margin-top: 4rem;
      }

      a,
      button {
        padding: 0;
        margin: 0;
        border: 0;
        background-color: transparent;
        font-family: var(--variable-font-family-brand);
        font-size: 9vw;
        color: var(--color-white);
        text-decoration: none;
      }
    }
  }
</style>
