// app/components/PlayerProfile.tsx
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import type { Player } from '@/lib/database/schema';
import type { PlayerStats } from '@/lib/repository';
import { cn } from '@/lib/utils';

type PlayerProfileProps = {
	player: Player;
	stats: PlayerStats;
};

export default function PlayerProfile({ player, stats }: PlayerProfileProps) {
	return (
		<header className="player-profile mb-8 flex items-center justify-center gap-4">
			<Avatar className={cn('h-32 w-32 border-4 border-foreground')}>
				<AvatarImage src={player.picture ?? undefined} />
				<AvatarFallback>{player.name[0] + player.name[1]}</AvatarFallback>
			</Avatar>

			<div className="players-stats">
				<ul className="flex flex-col gap-2">
					<li>Partite giocate: {stats.matchesPlayedCount}</li>
					<li>Partite vinte: {stats.matchesWonCount}</li>
					<li>
						% di vincita:{' '}
						{Math.round(
							(stats.matchesWonCount / stats.matchesPlayedCount) * 100,
						)}
						%
					</li>
				</ul>
			</div>
		</header>
	);
}

// __old/src/components/PlayerProfile.svelte
<script lang="ts">
	import type { Player } from '../lib/server/db';
	import Avatar from './ui/Avatar/Avatar.svelte';
	import type { PlayerStats } from '../lib/server/db/repository';

	export let player: Player;
	export let stats: PlayerStats;
</script>

<header class="player-profile">
	<Avatar
		picture={player.picture || ''}
		name={player.name}
		size={120}
		className="player-profile-avatar"
	/>

	<div class="players-stats">
		<ul>
			<li>Partite giocate: {stats.matchesPlayedCount}</li>
			<li>Partite vinte: {stats.matchesWonCount}</li>
			<li>% di vincita: {Math.round((stats.matchesWonCount / stats.matchesPlayedCount) * 100)}%</li>
		</ul>
	</div>
</header>

<style lang="scss">
	.player-profile {
		display: grid;
		grid-template-columns: 1fr 1fr;
		align-items: center;
		justify-items: center;
		gap: 1rem;
		margin: 0 0 2rem 0;
	}

	:global(.player-profile-avatar) {
		grid-column: 1/2;
	}

	.players-stats {
		grid-column: 2/3;

		ul,
		li {
			margin: 0;
			padding: 0;
			list-style-type: none;
		}
	}
</style>
