// app/routes/tournaments.tsx
import { ChevronRight } from 'lucide-react';
import { Link, redirect } from 'react-router';
import Main from '@/components/Main';
import PageTitle from '@/components/PageTitle';
import { isUserAuthenticated } from '@/lib/auth';
import type { Match, Tournament } from '@/lib/database/schema';
import { getTournaments } from '@/lib/repository';
import type { Route } from './+types/tournaments';

export async function loader({ request, params }: Route.LoaderArgs) {
	const user = await isUserAuthenticated(request);
	if (!user) {
		return redirect('/signin');
	}

	const tournaments: Array<Tournament & { matches: Match[] }> =
		await getTournaments();

	return {
		tournaments,
	};
}

export default function TournamentsPage({ loaderData }: Route.ComponentProps) {
	const { tournaments } = loaderData;

	const activeTournament: Tournament & { matches: Match[] } = tournaments.find(
		(t) => t.isActive,
	);
	const otherTournaments: Array<
		Tournament & {
			matches: Match[];
		}
	> = tournaments.filter((t) => t.id !== activeTournament?.id);

	return (
		<Main>
			<div className="flex flex-col">
				<PageTitle title="Tornei" />
				<h2>Torneo attuale:</h2>

				{activeTournament && (
					<ul className="flex w-full flex-col items-center gap-4">
						<li>
							<Link to={`/leaderboard/${activeTournament.id}`}>
								<strong>{activeTournament.title}</strong>
								<ChevronRight size={24} />
							</Link>
						</li>
					</ul>
				)}

				{!activeTournament && <p>Non c'è un torneo attivo</p>}

				<h2>Tornei precedenti:</h2>
				{otherTournaments && otherTournaments.length > 0 && (
					<ul className="flex w-full flex-col items-center gap-4">
						{otherTournaments.map((t) => (
							<li key={t.id}>
								<Link to={`/leaderboard/${t.id}`}>
									<strong>{t.title}</strong>
									<ChevronRight size={24} />
								</Link>
							</li>
						))}
					</ul>
				)}

				{!otherTournaments ||
					(otherTournaments.length === 0 && <p>Non ci sono altri tornei.</p>)}
			</div>
		</Main>
	);
}

// src/routes/(app)/tournaments/+page.svelte
<script lang="ts">
	import Main from '$components/Main.svelte';
	import PageTitle from '$components/PageTitle.svelte';
	import type { PageProps } from './$types';
	import { ChevronRight } from '@lucide/svelte';
	import { buttonVariants } from '$lib/components/ui/button';
	import { cn } from '$lib/utils';

	let { data }: PageProps = $props();
	const { tournaments } = data;

	const activeTournament = tournaments.find((t) => t.isActive);
	const otherTournaments = tournaments.filter((t) => t.id !== activeTournament?.id);
</script>

<Main className="user-page">
	<div class="flex flex-col gap-4 justify-center items-center">
		<PageTitle title="Tornei" />

		<h2 class="mb-4">Torneo attuale:</h2>

		{#if activeTournament}
			<ul class="flex w-full flex-col items-center gap-4">
				<li class="h-12">
					<a href={`/leaderboard/${activeTournament.id}`}
						 class={cn(
							 buttonVariants({variant: "secondary"}),
							 "h-12 w-full bg-indigo-500 hover:bg-indigo-700"
							 )}>
						<strong>{activeTournament.title}</strong>
						<ChevronRight size="24" />
					</a>
				</li>
			</ul>
		{:else}
			<p class="mb-4">Non c'è un torneo attivo</p>
		{/if}

		<h2 class="mb-4">Tornei precedenti:</h2>
		{#if otherTournaments && otherTournaments.length > 0}
			<ul class="flex w-full flex-col items-center gap-4">
				{#each otherTournaments as t}
					<li class="h-12">
						<a href={`/leaderboard/${t.id}`}
							 class={cn(
							 buttonVariants({variant: "secondary"}),
							 "h-12 w-full bg-indigo-500 hover:bg-indigo-700"
							 )}>
							<strong>{t.title}</strong>
							<ChevronRight size="24" />
						</a>
					</li>
				{/each}
			</ul>
		{:else}
			<p class="mb-4">Non ci sono altri tornei.</p>
		{/if}
	</div>
</Main>
